from pymycobot import MyCobot280
import time

mc = MyCobot280("COM4", 115200)
mc.power_on()
time.sleep(2)
angles = mc.get_angles()
print(angles)

reply= mc.send_angle(1, 0, 30)
print(reply)
time.sleep(2)
print( mc.get_angles())
reply= mc.send_angle(1, 60, 30)
print(reply)
time.sleep(2)
print( mc.get_angles())
reply= mc.send_angle(2, -45, 30)
print(reply)
time.sleep(2)
print( mc.get_angles())
reply= mc.send_angle(3, 20, 30)
print(reply)
time.sleep(2)
print( mc.get_angles())
reply= mc.send_angle(4, 45, 30)
print(reply)
time.sleep(2)
print( mc.get_angles())
reply= mc.send_angle(5, 90, 30)
print(reply)
time.sleep(2)
print( mc.get_angles())
reply= mc.send_angle(1, 25, 30)
print(reply)
time.sleep(2)
print( mc.get_angles())

for i in range(1, 7):
    mc.send_angle(i, 0, 5)
    time.sleep(2)